name: Publish JAR to GitHub Packages

on:
  push:
    branches:
      - main  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build JAR 
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy -s .github/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
